/* СГЕНЕРИРОВАНО. Не править руками — правится контракт, потом `pnpm run gen:contract`.
 * Источник: Тили-тили_API_openapi.yaml (версия 0.45.0).
 * Операций: 188. Путей: 140. */

export interface ContractOperation {
  /** HTTP-метод в верхнем регистре. */
  readonly method: string
  /** Путь как в контракте: /weddings/{weddingId}. */
  readonly openapi: string
  /** Тот же путь в нотации Fastify: /weddings/:weddingId. */
  readonly url: string
  readonly operationId: string | null
  readonly summary: string
  readonly tag: string | null
}

export const CONTRACT_OPERATIONS: readonly ContractOperation[] = [
  {"method":"GET","openapi":"/admin/categories","url":"/admin/categories","operationId":null,"summary":"Категории и словарь синонимов","tag":"admin"},
  {"method":"PUT","openapi":"/admin/categories","url":"/admin/categories","operationId":null,"summary":"Изменить категории и словарь синонимов","tag":"admin"},
  {"method":"GET","openapi":"/admin/complaints","url":"/admin/complaints","operationId":null,"summary":"Очередь жалоб","tag":"admin"},
  {"method":"POST","openapi":"/admin/complaints/{complaintId}","url":"/admin/complaints/:complaintId","operationId":null,"summary":"Решение по жалобе","tag":"admin"},
  {"method":"GET","openapi":"/admin/concierge","url":"/admin/concierge","operationId":null,"summary":"Очередь заявок консьержу","tag":"admin"},
  {"method":"POST","openapi":"/admin/concierge/{requestId}","url":"/admin/concierge/:requestId","operationId":null,"summary":"Состояние заявки консьержу","tag":"admin"},
  {"method":"GET","openapi":"/admin/metrics","url":"/admin/metrics","operationId":null,"summary":"Дашборд платформы","tag":"admin"},
  {"method":"GET","openapi":"/admin/moderation/vendors","url":"/admin/moderation/vendors","operationId":null,"summary":"Очередь пост-модерации анкет","tag":"admin"},
  {"method":"POST","openapi":"/admin/moderation/vendors/{vendorId}","url":"/admin/moderation/vendors/:vendorId","operationId":null,"summary":"Решение по анкете","tag":"admin"},
  {"method":"GET","openapi":"/admin/verifications","url":"/admin/verifications","operationId":null,"summary":"Очередь заявок на верификацию","tag":"admin"},
  {"method":"GET","openapi":"/admin/verifications/{requestId}","url":"/admin/verifications/:requestId","operationId":null,"summary":"Карточка заявки на верификацию","tag":"admin"},
  {"method":"POST","openapi":"/admin/verifications/{requestId}","url":"/admin/verifications/:requestId","operationId":null,"summary":"Решение по заявке на верификацию","tag":"admin"},
  {"method":"GET","openapi":"/admin/weddings/{weddingId}","url":"/admin/weddings/:weddingId","operationId":null,"summary":"Просмотр проекта поддержкой","tag":"admin"},
  {"method":"GET","openapi":"/admin/weddings/{weddingId}/deals","url":"/admin/weddings/:weddingId/deals","operationId":null,"summary":"Сделки свадьбы для поддержки (только чтение, с причиной и записью в журнал)","tag":"admin"},
  {"method":"GET","openapi":"/auth/oauth/{provider}","url":"/auth/oauth/:provider","operationId":null,"summary":"OAuth-вход (VK, Yandex, Google, Telegram)","tag":"auth"},
  {"method":"POST","openapi":"/auth/otp","url":"/auth/otp","operationId":null,"summary":"Запросить код из SMS","tag":"auth"},
  {"method":"POST","openapi":"/auth/otp/verify","url":"/auth/otp/verify","operationId":null,"summary":"Обменять код на токены","tag":"auth"},
  {"method":"POST","openapi":"/auth/refresh","url":"/auth/refresh","operationId":null,"summary":"Обновление access-token","tag":"auth"},
  {"method":"GET","openapi":"/catalog/categories","url":"/catalog/categories","operationId":null,"summary":"Категории подрядчиков (площадки, фото, декор…)","tag":"catalog"},
  {"method":"POST","openapi":"/catalog/concierge","url":"/catalog/concierge","operationId":null,"summary":"Заявка консьержу при пустой выдаче","tag":"catalog"},
  {"method":"GET","openapi":"/catalog/vendors","url":"/catalog/vendors","operationId":null,"summary":"Каталог подрядчиков с фильтрами","tag":"catalog"},
  {"method":"GET","openapi":"/catalog/vendors/{vendorId}","url":"/catalog/vendors/:vendorId","operationId":null,"summary":"Анкета подрядчика","tag":"catalog"},
  {"method":"GET","openapi":"/catalog/vendors/{vendorId}/availability","url":"/catalog/vendors/:vendorId/availability","operationId":null,"summary":"Занятость дат (для выбора даты брони)","tag":"catalog"},
  {"method":"GET","openapi":"/catalog/vendors/{vendorId}/reviews","url":"/catalog/vendors/:vendorId/reviews","operationId":null,"summary":"Отзывы о подрядчике","tag":"catalog"},
  {"method":"POST","openapi":"/catalog/vendors/{vendorId}/reviews","url":"/catalog/vendors/:vendorId/reviews","operationId":null,"summary":"Оставить отзыв (только после завершённой сделки)","tag":"catalog"},
  {"method":"GET","openapi":"/chats","url":"/chats","operationId":null,"summary":"Список чатов пользователя","tag":"chats"},
  {"method":"GET","openapi":"/chats/{chatId}/messages","url":"/chats/:chatId/messages","operationId":null,"summary":"История сообщений","tag":"chats"},
  {"method":"POST","openapi":"/chats/{chatId}/messages","url":"/chats/:chatId/messages","operationId":null,"summary":"Отправить сообщение","tag":"chats"},
  {"method":"POST","openapi":"/chats/{chatId}/typing","url":"/chats/:chatId/typing","operationId":null,"summary":"Индикатор «печатает…» (WebSocket-fallback)","tag":"chats"},
  {"method":"GET","openapi":"/chats/{chatId}/ws","url":"/chats/:chatId/ws","operationId":null,"summary":"Живой канал чата (WebSocket)","tag":"chats"},
  {"method":"POST","openapi":"/chats/vendor/{vendorId}","url":"/chats/vendor/:vendorId","operationId":null,"summary":"Открыть/создать чат с подрядчиком («Написать»)","tag":"chats"},
  {"method":"POST","openapi":"/complaints","url":"/complaints","operationId":null,"summary":"Пожаловаться","tag":"moderation"},
  {"method":"PATCH","openapi":"/deals/{dealId}","url":"/deals/:dealId","operationId":null,"summary":"Перевести сделку в следующее состояние или исправить сумму","tag":"bookings"},
  {"method":"POST","openapi":"/deals/{dealId}/contract","url":"/deals/:dealId/contract","operationId":null,"summary":"Сгенерировать договор из шаблона","tag":"documents"},
  {"method":"GET","openapi":"/deals/{dealId}/events","url":"/deals/:dealId/events","operationId":null,"summary":"Журнал сделки","tag":"deals"},
  {"method":"GET","openapi":"/geo/cities","url":"/geo/cities","operationId":null,"summary":"Поиск городов (автокомплит CityPicker)","tag":"geo"},
  {"method":"GET","openapi":"/geo/nearest","url":"/geo/nearest","operationId":null,"summary":"Ближайший город по координатам (кнопка геолокации)","tag":"geo"},
  {"method":"GET","openapi":"/gifts/{guestToken}","url":"/gifts/:guestToken","operationId":null,"summary":"Список подарков глазами гостя","tag":"wishlist-guest"},
  {"method":"POST","openapi":"/gifts/{guestToken}/{giftId}/fund","url":"/gifts/:guestToken/:giftId/fund","operationId":null,"summary":"Внести часть суммы (складчина)","tag":"wishlist-guest"},
  {"method":"DELETE","openapi":"/gifts/{guestToken}/{giftId}/reserve","url":"/gifts/:guestToken/:giftId/reserve","operationId":null,"summary":"Снять свой резерв","tag":"wishlist-guest"},
  {"method":"POST","openapi":"/gifts/{guestToken}/{giftId}/reserve","url":"/gifts/:guestToken/:giftId/reserve","operationId":null,"summary":"Зарезервировать подарок","tag":"wishlist-guest"},
  {"method":"POST","openapi":"/gifts/{guestToken}/funds/{fundId}","url":"/gifts/:guestToken/funds/:fundId","operationId":null,"summary":"Перевод в денежный фонд","tag":"wishlist-guest"},
  {"method":"GET","openapi":"/guest-vendor/{token}","url":"/guest-vendor/:token","operationId":null,"summary":"Кабинет гостя-подрядчика","tag":"bookings"},
  {"method":"GET","openapi":"/guest-vendor/{token}/messages","url":"/guest-vendor/:token/messages","operationId":null,"summary":"Переписка своего подрядчика с парой","tag":"bookings"},
  {"method":"POST","openapi":"/guest-vendor/{token}/messages","url":"/guest-vendor/:token/messages","operationId":null,"summary":"Написать паре","tag":"bookings"},
  {"method":"GET","openapi":"/health","url":"/health","operationId":null,"summary":"Жив ли процесс","tag":"health"},
  {"method":"GET","openapi":"/health/ready","url":"/health/ready","operationId":null,"summary":"Готов ли принимать трафик","tag":"health"},
  {"method":"GET","openapi":"/inspiration/likes","url":"/inspiration/likes","operationId":null,"summary":"Избранные истории","tag":"catalog"},
  {"method":"DELETE","openapi":"/inspiration/likes/{storyId}","url":"/inspiration/likes/:storyId","operationId":null,"summary":"Снять отметку","tag":"catalog"},
  {"method":"PUT","openapi":"/inspiration/likes/{storyId}","url":"/inspiration/likes/:storyId","operationId":null,"summary":"Отметить историю","tag":"catalog"},
  {"method":"GET","openapi":"/invite/{shareCode}","url":"/invite/:shareCode","operationId":null,"summary":"Обменять одноразовый код на персональный токен гостя","tag":"guests"},
  {"method":"DELETE","openapi":"/invites/{code}","url":"/invites/:code","operationId":null,"summary":"Отозвать приглашение","tag":"invites"},
  {"method":"GET","openapi":"/invites/{code}","url":"/invites/:code","operationId":null,"summary":"Просмотр приглашения (экран /join/:code)","tag":"invites"},
  {"method":"POST","openapi":"/invites/{code}/accept","url":"/invites/:code/accept","operationId":null,"summary":"Принять приглашение (после регистрации/входа)","tag":"invites"},
  {"method":"GET","openapi":"/join/{guestToken}/day","url":"/join/:guestToken/day","operationId":null,"summary":"День свадьбы глазами гостя","tag":"logistics-guest"},
  {"method":"GET","openapi":"/join/{guestToken}/day-chat/messages","url":"/join/:guestToken/day-chat/messages","operationId":null,"summary":"Чат дня X глазами гостя","tag":"logistics-guest"},
  {"method":"POST","openapi":"/join/{guestToken}/day-chat/messages","url":"/join/:guestToken/day-chat/messages","operationId":null,"summary":"Гость пишет в чат дня X","tag":"logistics-guest"},
  {"method":"GET","openapi":"/join/{guestToken}/hotels","url":"/join/:guestToken/hotels","operationId":null,"summary":"Отельные блоки для гостя","tag":"logistics-guest"},
  {"method":"POST","openapi":"/join/{guestToken}/hotels","url":"/join/:guestToken/hotels","operationId":null,"summary":"Гость занимает номер в блоке","tag":"logistics-guest"},
  {"method":"GET","openapi":"/join/{guestToken}/menu-vote","url":"/join/:guestToken/menu-vote","operationId":null,"summary":"Опрос по горячему глазами гостя","tag":"logistics-guest"},
  {"method":"POST","openapi":"/join/{guestToken}/menu-vote","url":"/join/:guestToken/menu-vote","operationId":null,"summary":"Гость выбирает блюдо","tag":"catering"},
  {"method":"GET","openapi":"/join/{guestToken}/shuttle","url":"/join/:guestToken/shuttle","operationId":null,"summary":"Маршруты трансфера, доступные гостю","tag":"logistics-guest"},
  {"method":"POST","openapi":"/join/{guestToken}/shuttle","url":"/join/:guestToken/shuttle","operationId":null,"summary":"Гость записывается в автобус","tag":"logistics-guest"},
  {"method":"GET","openapi":"/join/{guestToken}/team","url":"/join/:guestToken/team","operationId":null,"summary":"Кто работал на свадьбе — глазами гостя","tag":"logistics-guest"},
  {"method":"GET","openapi":"/legal/policy","url":"/legal/policy","operationId":null,"summary":"Действующая редакция оферты и политики","tag":"legal"},
  {"method":"GET","openapi":"/me/favorites","url":"/me/favorites","operationId":null,"summary":"Избранное пользователя","tag":"catalog"},
  {"method":"DELETE","openapi":"/me/favorites/{vendorId}","url":"/me/favorites/:vendorId","operationId":null,"summary":"Убрать из избранного","tag":"catalog"},
  {"method":"PUT","openapi":"/me/favorites/{vendorId}","url":"/me/favorites/:vendorId","operationId":null,"summary":"Добавить в избранное","tag":"catalog"},
  {"method":"POST","openapi":"/media/upload-url","url":"/media/upload-url","operationId":null,"summary":"Ссылка для прямой загрузки файла","tag":"media"},
  {"method":"GET","openapi":"/notifications","url":"/notifications","operationId":null,"summary":"Уведомления пользователя","tag":"notifications"},
  {"method":"POST","openapi":"/notifications/{id}/read","url":"/notifications/:id/read","operationId":null,"summary":"Отметить прочитанным","tag":"notifications"},
  {"method":"POST","openapi":"/notifications/read-all","url":"/notifications/read-all","operationId":null,"summary":"Отметить прочитанными все","tag":"notifications"},
  {"method":"POST","openapi":"/referral/{code}/apply","url":"/referral/:code/apply","operationId":null,"summary":"Применить чужой реферальный код","tag":"auth"},
  {"method":"GET","openapi":"/rsvp/{guestToken}","url":"/rsvp/:guestToken","operationId":null,"summary":"Публичная страница гостя (из ссылки в приглашении)","tag":"guests"},
  {"method":"POST","openapi":"/rsvp/{guestToken}","url":"/rsvp/:guestToken","operationId":null,"summary":"Ответ гостя (RSVP)","tag":"guests"},
  {"method":"DELETE","openapi":"/users/me","url":"/users/me","operationId":null,"summary":"Удалить аккаунт","tag":"auth"},
  {"method":"GET","openapi":"/users/me","url":"/users/me","operationId":null,"summary":"Мой профиль","tag":"auth"},
  {"method":"PATCH","openapi":"/users/me","url":"/users/me","operationId":null,"summary":"Изменить профиль и настройки уведомлений","tag":"auth"},
  {"method":"DELETE","openapi":"/users/me/consent","url":"/users/me/consent","operationId":null,"summary":"Отозвать согласие","tag":"auth"},
  {"method":"POST","openapi":"/users/me/consent","url":"/users/me/consent","operationId":null,"summary":"Зафиксировать согласие на обработку персональных данных","tag":"auth"},
  {"method":"GET","openapi":"/users/me/export","url":"/users/me/export","operationId":null,"summary":"Экспорт моих данных","tag":"auth"},
  {"method":"DELETE","openapi":"/users/me/push-subscriptions","url":"/users/me/push-subscriptions","operationId":null,"summary":"Отписаться от push","tag":"notifications"},
  {"method":"GET","openapi":"/users/me/push-subscriptions","url":"/users/me/push-subscriptions","operationId":null,"summary":"Мои push-подписки","tag":"notifications"},
  {"method":"POST","openapi":"/users/me/push-subscriptions","url":"/users/me/push-subscriptions","operationId":null,"summary":"Зарегистрировать подписку Web Push","tag":"notifications"},
  {"method":"GET","openapi":"/users/me/referral","url":"/users/me/referral","operationId":null,"summary":"Мой реферальный код и начисления","tag":"auth"},
  {"method":"DELETE","openapi":"/users/me/sessions","url":"/users/me/sessions","operationId":null,"summary":"Выйти со всех устройств, кроме текущего","tag":"auth"},
  {"method":"GET","openapi":"/users/me/sessions","url":"/users/me/sessions","operationId":null,"summary":"Мои сессии и устройства","tag":"auth"},
  {"method":"DELETE","openapi":"/users/me/sessions/{sessionId}","url":"/users/me/sessions/:sessionId","operationId":null,"summary":"Завершить сессию","tag":"auth"},
  {"method":"GET","openapi":"/vendor/analytics","url":"/vendor/analytics","operationId":null,"summary":"Аналитика анкеты (просмотры → лиды → сделки)","tag":"vendor"},
  {"method":"GET","openapi":"/vendor/calendar","url":"/vendor/calendar","operationId":null,"summary":"Занятость (календарь подрядчика)","tag":"vendor"},
  {"method":"POST","openapi":"/vendor/calendar/busy","url":"/vendor/calendar/busy","operationId":null,"summary":"Отметить даты занятыми/свободными","tag":"vendor"},
  {"method":"GET","openapi":"/vendor/deals","url":"/vendor/deals","operationId":null,"summary":"Сделки подрядчика","tag":"vendor"},
  {"method":"GET","openapi":"/vendor/leads","url":"/vendor/leads","operationId":null,"summary":"Входящие лиды","tag":"vendor"},
  {"method":"POST","openapi":"/vendor/leads/{leadId}","url":"/vendor/leads/:leadId","operationId":null,"summary":"Действие с лидом: ответить / холд 72ч / отклонить / вернуть","tag":"vendor"},
  {"method":"GET","openapi":"/vendor/profile","url":"/vendor/profile","operationId":null,"summary":"Моя анкета подрядчика","tag":"vendor"},
  {"method":"PUT","openapi":"/vendor/profile","url":"/vendor/profile","operationId":null,"summary":"Создать/обновить анкету (мастер: категория → пакеты → город → публикация)","tag":"vendor"},
  {"method":"POST","openapi":"/vendor/profile/publish","url":"/vendor/profile/publish","operationId":null,"summary":"Опубликовать анкету (модерация → live)","tag":"vendor"},
  {"method":"GET","openapi":"/vendor/reviews","url":"/vendor/reviews","operationId":null,"summary":"Отзывы на меня","tag":"vendor"},
  {"method":"POST","openapi":"/vendor/reviews/{reviewId}/reply","url":"/vendor/reviews/:reviewId/reply","operationId":null,"summary":"Ответить на отзыв","tag":"vendor"},
  {"method":"GET","openapi":"/vendor/updates","url":"/vendor/updates","operationId":null,"summary":"Обновления от пар","tag":"vendor"},
  {"method":"POST","openapi":"/vendor/updates/{updateId}/ack","url":"/vendor/updates/:updateId/ack","operationId":null,"summary":"Подтвердить получение обновления","tag":"vendor"},
  {"method":"GET","openapi":"/vendor/verification","url":"/vendor/verification","operationId":null,"summary":"Состояние моей заявки на верификацию","tag":"vendor"},
  {"method":"POST","openapi":"/vendor/verification","url":"/vendor/verification","operationId":null,"summary":"Подать документы на верификацию","tag":"vendor"},
  {"method":"GET","openapi":"/weddings","url":"/weddings","operationId":null,"summary":"Мои свадьбы","tag":"weddings"},
  {"method":"POST","openapi":"/weddings","url":"/weddings","operationId":null,"summary":"Создать свадьбу (после квиза)","tag":"weddings"},
  {"method":"GET","openapi":"/weddings/{weddingId}","url":"/weddings/:weddingId","operationId":null,"summary":"Карточка свадьбы (данные для Home)","tag":"weddings"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}","url":"/weddings/:weddingId","operationId":null,"summary":"Обновить (дата, город, бюджет, стиль)","tag":"weddings"},
  {"method":"GET","openapi":"/weddings/{weddingId}/album","url":"/weddings/:weddingId/album","operationId":null,"summary":"Общий фотоальбом гостей","tag":"album"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/album","url":"/weddings/:weddingId/album","operationId":null,"summary":"Одобрить или скрыть все кадры разом","tag":"album"},
  {"method":"POST","openapi":"/weddings/{weddingId}/album","url":"/weddings/:weddingId/album","operationId":null,"summary":"Гость добавляет фото","tag":"album"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/album/{photoId}","url":"/weddings/:weddingId/album/:photoId","operationId":null,"summary":"Одобрить или скрыть кадр","tag":"album"},
  {"method":"PUT","openapi":"/weddings/{weddingId}/anti-gifts","url":"/weddings/:weddingId/anti-gifts","operationId":null,"summary":"Список «просим не дарить»","tag":"wishlist"},
  {"method":"GET","openapi":"/weddings/{weddingId}/budget","url":"/weddings/:weddingId/budget","operationId":null,"summary":"Бюджет (статьи + автосуммы из слотов)","tag":"budget"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/budget/categories/{categoryId}/limit","url":"/weddings/:weddingId/budget/categories/:categoryId/limit","operationId":null,"summary":"Вернуть автоматический лимит категории с проверкой версии","tag":"budget"},
  {"method":"PUT","openapi":"/weddings/{weddingId}/budget/categories/{categoryId}/limit","url":"/weddings/:weddingId/budget/categories/:categoryId/limit","operationId":null,"summary":"Задать пользовательский лимит категории","tag":"budget"},
  {"method":"POST","openapi":"/weddings/{weddingId}/budget/items","url":"/weddings/:weddingId/budget/items","operationId":null,"summary":"Своя статья расхода","tag":"budget"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/budget/items/{itemId}","url":"/weddings/:weddingId/budget/items/:itemId","operationId":null,"summary":"Удалить свою статью (×-кнопка)","tag":"budget"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/budget/settings","url":"/weddings/:weddingId/budget/settings","operationId":null,"summary":"Изменить резерв бюджета","tag":"budget"},
  {"method":"POST","openapi":"/weddings/{weddingId}/cancel","url":"/weddings/:weddingId/cancel","operationId":null,"summary":"Отменить свадьбу","tag":"weddings"},
  {"method":"GET","openapi":"/weddings/{weddingId}/documents","url":"/weddings/:weddingId/documents","operationId":null,"summary":"Договоры свадьбы","tag":"documents"},
  {"method":"POST","openapi":"/weddings/{weddingId}/funds","url":"/weddings/:weddingId/funds","operationId":null,"summary":"Завести денежный фонд","tag":"wishlist"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/funds/{fundId}","url":"/weddings/:weddingId/funds/:fundId","operationId":null,"summary":"Удалить фонд","tag":"wishlist"},
  {"method":"GET","openapi":"/weddings/{weddingId}/guest-reviews","url":"/weddings/:weddingId/guest-reviews","operationId":null,"summary":"Отзывы гостей о подрядчиках (для пары)","tag":"reviews"},
  {"method":"POST","openapi":"/weddings/{weddingId}/guest-reviews","url":"/weddings/:weddingId/guest-reviews","operationId":null,"summary":"Гость оставляет отзыв","tag":"reviews"},
  {"method":"GET","openapi":"/weddings/{weddingId}/guests","url":"/weddings/:weddingId/guests","operationId":null,"summary":"Список гостей","tag":"guests"},
  {"method":"POST","openapi":"/weddings/{weddingId}/guests","url":"/weddings/:weddingId/guests","operationId":null,"summary":"Добавить гостя","tag":"guests"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/guests/{guestId}","url":"/weddings/:weddingId/guests/:guestId","operationId":null,"summary":"Удалить гостя","tag":"guests"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/guests/{guestId}","url":"/weddings/:weddingId/guests/:guestId","operationId":null,"summary":"Обновить гостя (статус RSVP циклом yes→no→pending)","tag":"guests"},
  {"method":"POST","openapi":"/weddings/{weddingId}/guests/{guestId}/invite-link","url":"/weddings/:weddingId/guests/:guestId/invite-link","operationId":null,"summary":"Выдать (или перевыпустить) одноразовую ссылку-приглашение гостю","tag":"guests"},
  {"method":"POST","openapi":"/weddings/{weddingId}/guests/import","url":"/weddings/:weddingId/guests/import","operationId":null,"summary":"Завести гостей списком","tag":"guests"},
  {"method":"POST","openapi":"/weddings/{weddingId}/guests/remind","url":"/weddings/:weddingId/guests/remind","operationId":null,"summary":"Напомнить гостям, которые не ответили","tag":"guests"},
  {"method":"GET","openapi":"/weddings/{weddingId}/invites","url":"/weddings/:weddingId/invites","operationId":null,"summary":"Активные приглашения","tag":"invites"},
  {"method":"POST","openapi":"/weddings/{weddingId}/invites","url":"/weddings/:weddingId/invites","operationId":null,"summary":"Создать одноразовую ссылку-приглашение (7 дней)","tag":"invites"},
  {"method":"GET","openapi":"/weddings/{weddingId}/logistics/buses","url":"/weddings/:weddingId/logistics/buses","operationId":null,"summary":"Маршруты трансфера","tag":"logistics"},
  {"method":"POST","openapi":"/weddings/{weddingId}/logistics/buses","url":"/weddings/:weddingId/logistics/buses","operationId":null,"summary":"Добавить маршрут трансфера","tag":"logistics"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/logistics/buses/{busId}","url":"/weddings/:weddingId/logistics/buses/:busId","operationId":null,"summary":"Удалить маршрут","tag":"logistics"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/logistics/buses/{busId}","url":"/weddings/:weddingId/logistics/buses/:busId","operationId":null,"summary":"Изменить маршрут","tag":"logistics"},
  {"method":"GET","openapi":"/weddings/{weddingId}/logistics/hotels","url":"/weddings/:weddingId/logistics/hotels","operationId":null,"summary":"Отельные блоки","tag":"logistics"},
  {"method":"POST","openapi":"/weddings/{weddingId}/logistics/hotels","url":"/weddings/:weddingId/logistics/hotels","operationId":null,"summary":"Добавить отельный блок","tag":"logistics"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/logistics/hotels/{hotelId}","url":"/weddings/:weddingId/logistics/hotels/:hotelId","operationId":null,"summary":"Удалить отельный блок","tag":"logistics"},
  {"method":"POST","openapi":"/weddings/{weddingId}/logistics/notify-pickup","url":"/weddings/:weddingId/logistics/notify-pickup","operationId":null,"summary":"Разослать точки сбора записавшимся гостям","tag":"logistics"},
  {"method":"GET","openapi":"/weddings/{weddingId}/members","url":"/weddings/:weddingId/members","operationId":null,"summary":"Команда свадьбы","tag":"weddings"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/members/{userId}","url":"/weddings/:weddingId/members/:userId","operationId":null,"summary":"Удалить участника","tag":"weddings"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/members/{userId}","url":"/weddings/:weddingId/members/:userId","operationId":null,"summary":"Сменить роль участника (только couple)","tag":"weddings"},
  {"method":"GET","openapi":"/weddings/{weddingId}/menu-poll","url":"/weddings/:weddingId/menu-poll","operationId":null,"summary":"Опрос гостей по горячему","tag":"catering"},
  {"method":"PUT","openapi":"/weddings/{weddingId}/menu-poll","url":"/weddings/:weddingId/menu-poll","operationId":null,"summary":"Изменить опрос","tag":"catering"},
  {"method":"POST","openapi":"/weddings/{weddingId}/menu-poll/remind","url":"/weddings/:weddingId/menu-poll/remind","operationId":null,"summary":"Напомнить не выбравшим блюдо","tag":"catering"},
  {"method":"GET","openapi":"/weddings/{weddingId}/notes","url":"/weddings/:weddingId/notes","operationId":null,"summary":"Заметки и идеи свадьбы","tag":"wedding"},
  {"method":"POST","openapi":"/weddings/{weddingId}/notes","url":"/weddings/:weddingId/notes","operationId":null,"summary":"Добавить заметку","tag":"wedding"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/notes/{noteId}","url":"/weddings/:weddingId/notes/:noteId","operationId":null,"summary":"Удалить заметку","tag":"wedding"},
  {"method":"GET","openapi":"/weddings/{weddingId}/payment-schedule","url":"/weddings/:weddingId/payment-schedule","operationId":null,"summary":"График платежей, актуальные итоги и отметки оплат","tag":"budget"},
  {"method":"POST","openapi":"/weddings/{weddingId}/payment-schedule","url":"/weddings/:weddingId/payment-schedule","operationId":null,"summary":"Создать этап платежа","tag":"budget"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/payment-schedule/{installmentId}","url":"/weddings/:weddingId/payment-schedule/:installmentId","operationId":null,"summary":"Изменить или отменить плановый этап","tag":"budget"},
  {"method":"POST","openapi":"/weddings/{weddingId}/payment-schedule/{installmentId}/pay","url":"/weddings/:weddingId/payment-schedule/:installmentId/pay","operationId":null,"summary":"Отметить полную или частичную оплату этапа","tag":"budget"},
  {"method":"GET","openapi":"/weddings/{weddingId}/payment-schedule/export","url":"/weddings/:weddingId/payment-schedule/export","operationId":null,"summary":"Выгрузить историю планов и оплат в CSV","tag":"budget"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/payments/{paymentId}/plan","url":"/weddings/:weddingId/payments/:paymentId/plan","operationId":null,"summary":"Привязать существующую оплату к этапу без новой записи","tag":"budget"},
  {"method":"GET","openapi":"/weddings/{weddingId}/payments/{paymentId}/receipts","url":"/weddings/:weddingId/payments/:paymentId/receipts","operationId":null,"summary":"Приватные подтверждения оплаты","tag":"payments"},
  {"method":"POST","openapi":"/weddings/{weddingId}/payments/{paymentId}/receipts","url":"/weddings/:weddingId/payments/:paymentId/receipts","operationId":null,"summary":"Прикрепить приватное подтверждение оплаты","tag":"payments"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/payments/{paymentId}/receipts/{receiptId}","url":"/weddings/:weddingId/payments/:paymentId/receipts/:receiptId","operationId":null,"summary":"Удалить приватное подтверждение оплаты","tag":"payments"},
  {"method":"GET","openapi":"/weddings/{weddingId}/payments/{paymentId}/receipts/{receiptId}/content","url":"/weddings/:weddingId/payments/:paymentId/receipts/:receiptId/content","operationId":null,"summary":"Скачать приватное подтверждение оплаты","tag":"payments"},
  {"method":"GET","openapi":"/weddings/{weddingId}/planb","url":"/weddings/:weddingId/planb","operationId":null,"summary":"План Б: сценарий и чек-лист накануне","tag":"timeline"},
  {"method":"POST","openapi":"/weddings/{weddingId}/planb/activate","url":"/weddings/:weddingId/planb/activate","operationId":null,"summary":"Активировать план Б","tag":"timeline"},
  {"method":"POST","openapi":"/weddings/{weddingId}/reschedule","url":"/weddings/:weddingId/reschedule","operationId":null,"summary":"Перенести дату свадьбы","tag":"weddings"},
  {"method":"GET","openapi":"/weddings/{weddingId}/slots","url":"/weddings/:weddingId/slots","operationId":null,"summary":"Слоты команды: 12 из шаблона (площадка, фотограф, видеограф, ведущий, флорист, кондитер, стилист, DJ, декоратор, транспорт, платье, кольца) плюс добавленные парой","tag":"bookings"},
  {"method":"POST","openapi":"/weddings/{weddingId}/slots","url":"/weddings/:weddingId/slots","operationId":null,"summary":"Добавить слот категории в мозаику","tag":"bookings"},
  {"method":"POST","openapi":"/weddings/{weddingId}/slots/{slotId}/book","url":"/weddings/:weddingId/slots/:slotId/book","operationId":null,"summary":"Забронировать подрядчика в слот («Добавить в свадьбу»)","tag":"bookings"},
  {"method":"POST","openapi":"/weddings/{weddingId}/slots/{slotId}/cancel","url":"/weddings/:weddingId/slots/:slotId/cancel","operationId":null,"summary":"Отменить бронь (слот → free, бюджет минус)","tag":"bookings"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/slots/{slotId}/external","url":"/weddings/:weddingId/slots/:slotId/external","operationId":null,"summary":"Удалить своего подрядчика","tag":"bookings"},
  {"method":"POST","openapi":"/weddings/{weddingId}/slots/{slotId}/external","url":"/weddings/:weddingId/slots/:slotId/external","operationId":null,"summary":"Добавить своего подрядчика (не из каталога)","tag":"bookings"},
  {"method":"POST","openapi":"/weddings/{weddingId}/slots/{slotId}/external/invite","url":"/weddings/:weddingId/slots/:slotId/external/invite","operationId":null,"summary":"Ссылка-приглашение для своего подрядчика","tag":"bookings"},
  {"method":"POST","openapi":"/weddings/{weddingId}/slots/{slotId}/pay","url":"/weddings/:weddingId/slots/:slotId/pay","operationId":null,"summary":"Оплата слота (доплата/полная)","tag":"bookings"},
  {"method":"GET","openapi":"/weddings/{weddingId}/tables","url":"/weddings/:weddingId/tables","operationId":null,"summary":"Рассадка (столы + гости)","tag":"guests"},
  {"method":"POST","openapi":"/weddings/{weddingId}/tables","url":"/weddings/:weddingId/tables","operationId":null,"summary":"Добавить стол","tag":"guests"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/tables/{tableId}","url":"/weddings/:weddingId/tables/:tableId","operationId":null,"summary":"Удалить стол","tag":"guests"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/tables/{tableId}","url":"/weddings/:weddingId/tables/:tableId","operationId":null,"summary":"Переименовать стол или изменить вместимость","tag":"guests"},
  {"method":"GET","openapi":"/weddings/{weddingId}/tasks","url":"/weddings/:weddingId/tasks","operationId":null,"summary":"Чек-лист (шаблонные + свои задачи)","tag":"tasks"},
  {"method":"POST","openapi":"/weddings/{weddingId}/tasks","url":"/weddings/:weddingId/tasks","operationId":null,"summary":"Своя задача","tag":"tasks"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/tasks/{taskId}","url":"/weddings/:weddingId/tasks/:taskId","operationId":null,"summary":"Удалить свою задачу","tag":"tasks"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/tasks/{taskId}","url":"/weddings/:weddingId/tasks/:taskId","operationId":null,"summary":"Отметить/изменить задачу","tag":"tasks"},
  {"method":"GET","openapi":"/weddings/{weddingId}/timeline","url":"/weddings/:weddingId/timeline","operationId":null,"summary":"Тайминг дня","tag":"timeline"},
  {"method":"PUT","openapi":"/weddings/{weddingId}/timeline","url":"/weddings/:weddingId/timeline","operationId":null,"summary":"Заменить тайминг целиком","tag":"timeline"},
  {"method":"POST","openapi":"/weddings/{weddingId}/timeline/autogen","url":"/weddings/:weddingId/timeline/autogen","operationId":null,"summary":"Автоплан дня по забронированной команде","tag":"timeline"},
  {"method":"POST","openapi":"/weddings/{weddingId}/timeline/shift","url":"/weddings/:weddingId/timeline/shift","operationId":null,"summary":"Сдвинуть день X на N минут","tag":"timeline"},
  {"method":"GET","openapi":"/weddings/{weddingId}/tips","url":"/weddings/:weddingId/tips","operationId":null,"summary":"Подсказки Тиля по правилам (Бизнес-логика §3.14)","tag":"wedding"},
  {"method":"GET","openapi":"/weddings/{weddingId}/wishlist","url":"/weddings/:weddingId/wishlist","operationId":null,"summary":"Список желаний пары","tag":"wishlist"},
  {"method":"POST","openapi":"/weddings/{weddingId}/wishlist","url":"/weddings/:weddingId/wishlist","operationId":null,"summary":"Добавить желание","tag":"wishlist"},
  {"method":"DELETE","openapi":"/weddings/{weddingId}/wishlist/{giftId}","url":"/weddings/:weddingId/wishlist/:giftId","operationId":null,"summary":"Удалить желание","tag":"wishlist"},
  {"method":"PATCH","openapi":"/weddings/{weddingId}/wishlist/{giftId}","url":"/weddings/:weddingId/wishlist/:giftId","operationId":null,"summary":"Изменить желание","tag":"wishlist"},
] as const
