import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { randomInt, randomUUID } from 'node:crypto'
import type { FastifyInstance } from 'fastify'
import { buildApp } from '../src/app.js'
import { signAccessToken } from '../src/auth/tokens.js'

const DB=process.env.TEST_DATABASE_URL,SECRET='a'.repeat(48),money=(amount:number)=>({amount,currency:'RUB'})
describe.skipIf(!DB)('018-B: лимиты, резерв и приватные подтверждения',()=>{
 let app:FastifyInstance
 beforeAll(async()=>{app=await buildApp({env:'test',databaseUrl:DB??null,redisUrl:null,jwtAccessSecret:SECRET,jwtRefreshSecret:'b'.repeat(48),policyVersion:'2026-09-02'});await app.ready()})
 afterAll(async()=>{await app?.close()})
 async function user(){const id=randomUUID(),sid=randomUUID();await app.db!.query('insert into users(id,phone,name) values($1,$2,$3)',[id,'+79'+randomInt(100000000,999999999),'018B']);await app.db!.query('insert into sessions(id,user_id,refresh_hash) values($1,$2,$3)',[sid,id,randomUUID()]);await app.db!.query("insert into consents(id,user_id,policy_version,adult) values($1,$2,'2026-09-02',true)",[randomUUID(),id]);return{id,token:await signAccessToken(SECRET,{sub:id,sid})}}
 async function setup(){const owner=await user(),id=randomUUID(),slotId=randomUUID(),dealId=randomUUID();await app.db!.query("insert into weddings(id,owner_id,title,date,tz,budget_total,invite_code) values($1,$2,'018B','2027-06-14','Asia/Yekaterinburg',10000000,$3)",[id,owner.id,randomUUID()]);await app.db!.query("insert into wedding_members(wedding_id,user_id,role) values($1,$2,'couple')",[id,owner.id]);await app.db!.query("insert into slots(id,wedding_id,category_id,label) values($1,$2,'photo','Фото')",[slotId,id]);await app.db!.query("insert into deals(id,wedding_id,slot_id,external_name,state,price,booked_at) values($1,$2,$3,'Фото','booked',1000000,now())",[dealId,id,slotId]);await app.db!.query('update slots set deal_id=$2 where id=$1',[slotId,dealId]);return{id,owner,slotId,dealId}}
 const headers=(w:Awaited<ReturnType<typeof setup>>)=>({authorization:'Bearer '+w.owner.token})
 const budget=(w:Awaited<ReturnType<typeof setup>>)=>app.inject({method:'GET',url:`/weddings/${w.id}/budget`,headers:headers(w)})
 it('меняет резерв с optimistic version и не считает его расходом',async()=>{const w=await setup(),before=(await budget(w)).json();expect(before.reserveBps).toBe(1000);expect(before.settingsVersion).toBe(0);const a=await app.inject({method:'PATCH',url:`/weddings/${w.id}/budget/settings`,headers:headers(w),payload:{reserveBps:1500,version:0}});expect(a.statusCode,a.body).toBe(200);const stale=await app.inject({method:'PATCH',url:`/weddings/${w.id}/budget/settings`,headers:headers(w),payload:{reserveBps:2000,version:0}});expect(stale.statusCode).toBe(409);const after=(await budget(w)).json();expect(after.reserve).toEqual(money(1500000));expect(after.spent).toEqual(before.spent)})
 it('задаёт лимит категории, защищает stale edit и возвращает авто-лимит',async()=>{const w=await setup();const put=(version:number,amount:number)=>app.inject({method:'PUT',url:`/weddings/${w.id}/budget/categories/b2/limit`,headers:headers(w),payload:{amount:money(amount),version}});expect((await put(0,2500000)).statusCode).toBe(200);expect((await put(0,2600000)).statusCode).toBe(409);let b=(await budget(w)).json(),cat=b.categories.find((x:{id:string})=>x.id==='b2');expect(cat).toMatchObject({planned:money(2500000),limitCustom:true,limitVersion:1});expect((await app.inject({method:'PATCH',url:`/weddings/${w.id}/budget/categories/b2/limit`,headers:headers(w),payload:{reset:true,version:1}})).statusCode).toBe(204);b=(await budget(w)).json();cat=b.categories.find((x:{id:string})=>x.id==='b2');expect(cat.limitCustom).toBe(false);expect(cat.limitVersion).toBe(2);expect(cat.planned.amount).not.toBe(2500000)
   // A client that still has version=0 from before custom -> auto must not revive the limit (ABA).
   expect((await put(0,2700000)).statusCode).toBe(409)})
 it('не раскрывает новые финансовые пути helper',async()=>{const w=await setup(),helper=await user();await app.db!.query("insert into wedding_members(wedding_id,user_id,role) values($1,$2,'helper')",[w.id,helper.id]);const h={authorization:'Bearer '+helper.token};expect((await app.inject({method:'PATCH',url:`/weddings/${w.id}/budget/settings`,headers:h,payload:{reserveBps:1000,version:0}})).statusCode).toBe(403)})
 it('ограниченная роль получает 403 до валидации тела финансовой записи',async()=>{const w=await setup(),helper=await user();await app.db!.query("insert into wedding_members(wedding_id,user_id,role) values($1,$2,'helper')",[w.id,helper.id]);const r=await app.inject({method:'PATCH',url:`/weddings/${w.id}/budget/settings`,headers:{authorization:'Bearer '+helper.token},payload:{reserveBps:'not-a-number'}});expect(r.statusCode).toBe(403)})
 async function payment(w:Awaited<ReturnType<typeof setup>>){const r=await app.inject({method:'POST',url:`/weddings/${w.id}/slots/${w.slotId}/pay`,headers:{...headers(w),'idempotency-key':randomUUID()},payload:{amount:money(100000)}});expect(r.statusCode,r.body).toBe(200);return (await app.db!.query<{id:string}>('select id from payments where deal_id=$1 order by created_at desc',[w.dealId])).rows[0]!.id}
 const png=Buffer.from([137,80,78,71,13,10,26,10,0]).toString('base64')
 it('загружает, читает и удаляет приватное подтверждение без публичного URL',async()=>{const w=await setup(),pid=await payment(w);const add=await app.inject({method:'POST',url:`/weddings/${w.id}/payments/${pid}/receipts`,headers:{...headers(w),'idempotency-key':randomUUID()},payload:{filename:'чек.png',mimeType:'image/png',contentBase64:png}});expect(add.statusCode,add.body).toBe(201);const rid=add.json().id;const list=await app.inject({method:'GET',url:`/weddings/${w.id}/payments/${pid}/receipts`,headers:headers(w)});expect(list.json().items).toHaveLength(1);expect(list.body).not.toContain(png);const content=await app.inject({method:'GET',url:`/weddings/${w.id}/payments/${pid}/receipts/${rid}/content`,headers:headers(w)});expect(content.headers['cache-control']).toBe('no-store');expect(content.headers['x-content-type-options']).toBe('nosniff');expect(content.json()).toMatchObject({filename:'чек.png',mimeType:'image/png',contentBase64:png});expect((await app.inject({method:'DELETE',url:`/weddings/${w.id}/payments/${pid}/receipts/${rid}`,headers:headers(w)})).statusCode).toBe(204)})
 it('повтор загрузки с тем же ключом не создаёт второй файл',async()=>{const w=await setup(),pid=await payment(w),key=randomUUID(),req=()=>app.inject({method:'POST',url:`/weddings/${w.id}/payments/${pid}/receipts`,headers:{...headers(w),'idempotency-key':key},payload:{filename:'чек.png',mimeType:'image/png',contentBase64:png}});const first=await req(),second=await req();expect(first.statusCode).toBe(201);expect(second.statusCode).toBe(201);expect(second.headers['idempotent-replay']).toBe('true');expect(second.json().id).toBe(first.json().id);const {rows}=await app.db!.query<{n:number}>('select count(*)::int as n from payment_receipts where payment_id=$1',[pid]);expect(rows[0]!.n).toBe(1)})
 it('проверяет magic bytes, а не доверяет MIME из браузера',async()=>{const w=await setup(),pid=await payment(w);const r=await app.inject({method:'POST',url:`/weddings/${w.id}/payments/${pid}/receipts`,headers:{...headers(w),'idempotency-key':randomUUID()},payload:{filename:'fake.pdf',mimeType:'application/pdf',contentBase64:png}});expect(r.statusCode).toBe(422)})
 it('не даёт читать подтверждение из другой свадьбы и helper',async()=>{const w=await setup(),pid=await payment(w),add=await app.inject({method:'POST',url:`/weddings/${w.id}/payments/${pid}/receipts`,headers:{...headers(w),'idempotency-key':randomUUID()},payload:{filename:'x.png',mimeType:'image/png',contentBase64:png}}),rid=add.json().id;const other=await setup();expect((await app.inject({method:'GET',url:`/weddings/${other.id}/payments/${pid}/receipts/${rid}/content`,headers:headers(other)})).statusCode).toBe(404);const helper=await user();await app.db!.query("insert into wedding_members(wedding_id,user_id,role) values($1,$2,'helper')",[w.id,helper.id]);expect((await app.inject({method:'GET',url:`/weddings/${w.id}/payments/${pid}/receipts/${rid}/content`,headers:{authorization:'Bearer '+helper.token}})).statusCode).toBe(403)})
})
